FROM python:3.12-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY pyproject.toml README.md alembic.ini ./
COPY apps ./apps
COPY artifacts ./artifacts
COPY migrations ./migrations
COPY scripts ./scripts
COPY src ./src

RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir .

CMD ["python", "-m", "celery", "-A", "apps.worker.celery_app:celery_app", "worker", "-l", "info"]
